CREATE DATABASE QuanLyKhoHang;
USE QuanLyKhoHang;

CREATE TABLE ThongTinShop(
	ID INT NOT NULL PRIMARY KEY,
	TenShop NVARCHAR(50),
	DiaChi NVARCHAR(250),
	SDT NVARCHAR(50),
	Loichao NVARCHAR(100),
	logo IMAGE
);

CREATE TABLE DonViSP(
	IDdonvi INT NOT NULL PRIMARY KEY,
	TenDonvi NVARCHAR(50),
	ShopID INT FOREIGN KEY REFERENCES ThongTinShop(ID)
);

CREATE TABLE KhachHang(
	IDkh INT NOT NULL PRIMARY KEY,
	TenKH NVARCHAR(50),
	SDT INT,
	DiaChi NVARCHAR(200),
	Email NVARCHAR(50)
);

CREATE TABLE NhanVien(
	STT INT IDENTITY(1,1) PRIMARY KEY,
	usernv NVARCHAR(50) NOT NULL UNIQUE,
	tennv NVARCHAR(50),
	passnv VARCHAR(200)
);

CREATE TABLE NhapKho(
	masp INT NOT NULL PRIMARY KEY,
	tensp NVARCHAR(50),
	soluongsp INT,
	gianhapsp INT,
	giabansp INT,
	loaisp NVARCHAR(30),
	donvisp NVARCHAR(30),
	anhsp IMAGE,
	ngaynhapkho DATETIME,
	nvnhapkho NVARCHAR(50)
);

CREATE TABLE TonKho(
	masp INT NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES NhapKho(masp),
	tensp NVARCHAR(50),
	soluongsp INT,
	gianhapsp INT,
	giabansp INT,
	loaisp NVARCHAR(30),
	donvisp NVARCHAR(30),
	anhsp IMAGE,
	giamgia INT
);

CREATE TABLE HoaDon(
	IDPhieu INT NOT NULL PRIMARY KEY,
	HDmasp INT FOREIGN KEY REFERENCES TonKho(masp),
	HDtensp NVARCHAR(200),
	HDsl INT,
	HDdongia INT,
	HDloai NVARCHAR(50),
	HDdonvi NVARCHAR(50),
	HDtt INT,
	HDno INT,
	SDT INT,
	IDKH INT FOREIGN KEY REFERENCES KhachHang(IDkh),
	TenKH NVARCHAR(50),
	HDtime DATETIME,
	IDNV INT FOREIGN KEY REFERENCES NhanVien(STT),
	Nhanvien NVARCHAR(50),
	DonViSPID INT FOREIGN KEY REFERENCES DonViSP(IDdonvi),
);

CREATE TABLE Loaisp(
	IDloai INT NOT NULL PRIMARY KEY,
	TenLoai NVARCHAR(50),
	DonViSPID INT FOREIGN KEY REFERENCES DonViSP(IDdonvi)
);
